### ISSUE TITLE
Fails sometimes in CI but exit code stays 0

### ISSUE THREAD

**Issue by mhluska** [GoogleChrome/lighthouse-ci#116]
I get the following error sometimes:

```
Error: Lighthouse failed with exit code 1
```

Followed by:

```
  "runWarnings": [
    "Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FCP)"
  ],
```

And yet exit code seems to be 0

**Comment by patrickhulce** [comment]
Do you have a link to some build output of this happening? If `collect` fails then we exit `autorun` with that exit code...

https://github.com/GoogleChrome/lighthouse-ci/blob/18fcc3e730cc720756eba4b9a94a778b60d5e1e0/packages/cli/src/autorun/autorun.js#L114-L118

**Comment by mhluska** [comment]
I could email you the raw log for our travis build if that would help. Let me know if you need any other data that I can pass along.

**Comment by patrickhulce** [comment]
Wait you're just talking about the *build* exiting with `0`? Then yes it's absolutely that `lhci autorun` is being run in `after_success`. This is intentional and documented in the getting started guide. If you *want* the build to fail when collection fails (such as when you start using assertions) then yes move it to `script`

**Comment by mhluska** [comment]
That part I had just figured out. The other part that I haven't figured out is why this error occurs in the first place for a particular URL.

**Comment by patrickhulce** [comment]
Gotcha 👍 While it's definitely rarer on linux CLI, NO_FCP can happen for a lot of reasons that are typically page and use-case specific (see https://github.com/GoogleChrome/lighthouse/issues/6154, https://github.com/GoogleChrome/lighthouse/issues/6463), but since this is a core Lighthouse issue we'll track over there.
