### ISSUE TITLE
Ability to run without need for git history

### ISSUE THREAD

**Issue by JWesorick** [GoogleChrome/lighthouse-ci#151]
I'm trying to get this running on Heroku CI and my own server on a heroku hobby dyno. Everything has gone smooth except for stuff around using `git`. While `git` is available in the CI environment, there is no git repository setup in the directory (no `.git` folder.)

If would be nice to have some kind of fallback that does not prevent the upload from happening in `getCommitMessage`, `getAuthor`, `getAvatarUrl`, and `getAncestorHashForMaster`.

**Comment by JWesorick** [comment]
I'd also love to work on this but cannot figure out how to install the package from github when its nested in `packages/cli`.

**Comment by thasmo** [comment]
I'd also love to see the possibility of a git-independent usage of lhci; #5 seems to be a step in the right direction.

**Comment by patrickhulce** [comment]
Thanks for filing @JWesorick! I'm not sure about an automatic fallback because the canonical use case we want to support is per-commit/git-based, but we're definitely thinking about how to accommodate this use case.

In the meantime, I think we can add support for manual setting of all git-related context so that the commands can at least run successfully with the right environment variables set.

**Comment by JWesorick** [comment]
Heroku does provide the commit hash, its just in an environment variable. Maybe that would be enough?
