### ISSUE TITLE
Define a standard docker image for Lighthouse

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#164]
I believe this means upstreaming the work done here:

* https://github.com/GoogleChromeLabs/gulliver/tree/master/lighthouse_machine
* https://github.com/ebidel/lighthouse-ci/tree/master/builder

---------

The lighthouse service within should be easily accessible over HTTP.
I kind of preferred the basic REST api within `lighthouse_machine`, but perhaps we should chat more about the API.

@ebidel wanna take a first whack at this?

**Comment by patrickhulce** [comment]
Current status of this as it pertains to lighthouse-ci:

- We will define a docker image that contains all the *necessary* dependencies to run Lighthouse that can be used in GitlabCI, CircleCI, etc.
- This docker image will *not* be recommended as the way to run lighthouse in a stable environment, merely a convenience.

**Comment by patrickhulce** [comment]
Docker image documentation: https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/docker-client

Example of it live in action with Circle CI: https://github.com/patrickhulce/patrickhulce.com/blob/2c917f4d3a10f7cc730e16980a9e2422636cdd29/.circleci/config.yml

**Comment by iDVB** [comment]
@patrickhulce Definitely seems like there is some offline context missing here. 

> > I think the biggest issue with an official docker image is the set of expectations that folks will inevitably have for it as a stable environment that I'm nearly certain won't be true.

Can someone offer up exactly what these expectations that we're nearly certain won't be true are in fact?
We have a monorepo that uses the programmatic node lighthouse to run our tests. The intent was to have this run as part of the CI's docker container (not as an action) due to the nx managed dependency tree.

@connorjclark Can you spell out for us exactly what the considerations are when choosing to run Lighthouse in a container?

When you guys say: 
> "Due to the nature of performance measurement and volatility of container-based resources in cloud environments, we strongly advise against using this Docker image when you have the ability to install Chrome directly."

What exactly is meant as "install Chrome directly"? 
Are we meaning directly to a long-running AWS EC2 vs any other Container based environment?
Where exactly is the issue?
