### ISSUE TITLE
Unable to modify server graphs

### ISSUE THREAD

**Issue by norchow** [GoogleChrome/lighthouse-ci#173]
Hello,
I'm trying to customize the graphs shown in the server to show other metrics such as FCP, TTI, etc.

The thing is that when I re-build the server image and start the container again, these changes are not taken into account.
Diving deeper into the code, I found that the server is being taken by the npm public package and not the local instance. What should I do in order to see my changes locally?

Thanks!

**Comment by patrickhulce** [comment]
You'd need to build your own container that runs the local code instead of running installing the node module. You're essentially forking lighthouse-ci server already, so just fork the `Dockerfile` too :)

**Comment by stefanteixeira** [comment]
@patrickhulce I want to show FCP, TTI and Speed Index in the dashboard, so I did these changes in the code:

packages/server/src/ui/routes/project-dashboard/project-graphs.jsx
```
return (
    <div className="dashboard-graphs">
      <Legend statistics={statsWithBuilds} builds={builds} branch={branch} />
      <StatisticPlot
        title="Performance"
        statisticName="category_performance_average"
        loadingState={loadingState}
        statistics={statsWithBuilds}
        builds={builds}
      />
      <StatisticPlot
        title="First Contentful Paint"
        statisticName="audit_first-contentful-paint_average"
        loadingState={loadingState}
        statistics={statsWithBuilds}
        builds={builds}
      />
      <StatisticPlot
        title="Time to Interactive"
        statisticName="audit_interactive_average"
        loadingState={loadingState}
        statistics={statsWithBuilds}
        builds={builds}
      />
      <StatisticPlot
        title="Speed Index"
        statisticName="audit_speed-index_average"
        loadingState={loadingState}
        statistics={statsWithBuilds}
        builds={builds}
      />
    </div>
  );
```

I did that change because I found in the code that these are existing values for StatisticName, on the definitions here: https://github.com/GoogleChrome/lighthouse-ci/blob/0f4dd6b64a9d2a138d78887bfb6e5c441f8eda54/packages/server/src/api/statistic-definitions.js

But the values are not getting plotted in the graphs, they are empty:

<img width="1418" alt="Screen Shot 2020-01-09 at 13 41 36" src="https://user-images.githubusercontent.com/4781037/72082036-50ec1880-32de-11ea-8133-89cd65cca95d.png">

How can I make this work? In my context, we need to keep close track of Performance and these three metrics (FCP, TTI, Speed Index), so if I could get these plotted in the dashboard it would be amazingly helpful for my team.

**Comment by patrickhulce** [comment]
I'm not sure why they're not coming through, do you see them if you hit the API directly? `/v1/projects/<projectId>/builds/<buildId>/statistics`.

While you are more then welcome to try to add this yourself and we're very pleased to see your enthusiasm :D, we don't really have the bandwidth to provide support to new features on forks at the moment. We plan to add this functionality to the main project in the coming months with a dashboard overhaul, so you could also hang tight til then :)
