### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by kaihendry** [GoogleChrome/lighthouse-ci#201]
Hi, I want to check a Website after deploying to it.

https://github.com/kaihendry/ltabus/blob/master/.travis.yml

Can you tell me where I am going wrong in my in my Travis file please? Most of your [docs](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md) assume some local site.

https://travis-ci.org/kaihendry/ltabus/builds/644249418

**Comment by patrickhulce** [comment]
> URL is not defined

This means your node version is out of date. Only node v10+ is supported. I don't actually see where you install node in your travis image. Either update where you install node to use v10 or v12 LTS or you can add nvm and node with something like...

```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
source ~/.nvm/nvm.sh
nvm install v12
```

> Most of your docs assume some local site.

Mostly because it's somewhat difficult to setup a system where every PR can be deployed to its own URL. If you want to only run `lhci` on your production URL you should modify your travis.yml to only collect LHCI results on tags. `after_deploy` is run after each deployment provider but you don't change the URL right now, so on master builds it will not be running against your newly deployed code.

**Comment by kaihendry** [comment]
Thank you for the reply. Is there a Makefile snippet or something that shows how to run on say localhost:3000 after I invoke `PORT=3000 go run main.go` or something like that?

**Comment by patrickhulce** [comment]
Yes, there are [example configurations](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#non-nodejs-server) for this exact scenario.

Also see the [CLI documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/cli.md#collect)
