### ISSUE TITLE
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.

### ISSUE THREAD

**Issue by sangotaro** [GoogleChrome/lighthouse-ci#258]
Running lhci server on k8s using `patrickhulce/lhci-server` image. When a pod restart occurs, a `RangeError` for the port is raised and the pod cannot be started successfully.

**Comment by patrickhulce** [comment]
Thanks for filing @sangotaro! Where are you seeing this error specifically? Do you have a stack trace or anything more?

I'm struggling to see how this could be coming from lhci given our extensive usage so far and the fact that the port is hardcoded to be `9001` in the docker image.

Is this a k8s error?

**Comment by sangotaro** [comment]
@patrickhulce 

Thanks for the reply.

This error is occurring in the lhci server (node.js). The following is a detailed error.

```
> lhci@0.0.0 start /usr/src/lhci
> lhci server --config=./lighthouserc.json

RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.
    at Server.listen (net.js:1406:13)
    at resolve (/usr/src/lhci/node_modules/@lhci/server/src/server.js:63:12)
    at new Promise (<anonymous>)
    at createServer (/usr/src/lhci/node_modules/@lhci/server/src/server.js:61:10)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lhci@0.0.0 start: `lhci server --config=./lighthouserc.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lhci@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-25T02_05_13_477Z-debug.log
```

This error does not occur the first time the pod is started, but when it is rebooted.

**Comment by patrickhulce** [comment]
Thanks @sangotaro! Has the docker image been modified or extended in any way or any custom configuration introduced via environment variables/config/etc? The `/usr/src/lhci/lighthouserc.json` file should contain a property `ci.server.port` set to `9001`.

The only way I can reproduce this is if I set `LHCI_PORT` to be something that's not a number or modify the configuration for port to something that's not a number. I'm guessing on pod restart something to this effect is happening that results in misconfiguration.

**Comment by sangotaro** [comment]
@patrickhulce

The docker image has not been extended. In addition, LHCI_PORT has not been set.

On the other hand, if I explicitly set LHCI_PORT to the container, it rebooted successfully. Is it possible that lighthouserc.json didn't load properly when the pod was restarted?

**Comment by patrickhulce** [comment]
> Is it possible that lighthouserc.json didn't load properly when the pod was restarted?

If that's true, the default value when there's no config is still a number so you would've just seen it booting on a different port. The only way this is possible I can see is if *something* is explicitly setting the port to something not a number, either via environment variable, CLI flag, or (a perhaps corrupted?) JSON config. The only thing left to check IMO is making sure `/usr/src/lhci/lighthouserc.json` didn't get accidentally modified somehow. 

I'm glad you got a workaround in place for now though.

**Comment by MahmoudDolah** [comment]
Just want to add to this and say that I've had the same exact error occur
Using the stock `lighthouserc.json` 
Not sure if it matters, but we're using kops on AWS and using a nodeport to expose the lighthouse-ci pod
```
root@7c4ff3a0432a:/usr/src/lhci# cat lighthouserc.json
{
  "ci": {
    "server": {
      "port": 9001,
      "storage": {
        "storageMethod": "sql",
        "sqlDialect": "sqlite",
        "sqlDatabasePath": "/data/lhci.db"
      }
    }
  }
}
```

**Comment by patrickhulce** [comment]
Thanks for the info @MahmoudDolah! Did you also resort to an environment override workaround?

**Comment by MahmoudDolah** [comment]
@patrickhulce I tried that but setting the environment variable didn't work for me

**Comment by patrickhulce** [comment]
@MahmoudDolah well *something* in the chain is setting the port to an invalid number. https://github.com/GoogleChrome/lighthouse-ci/pull/270 should add more debug information to help track it down.

**Comment by MahmoudDolah** [comment]
Just want to add to this (in case it helps anyone else), that when I delete the deployment and service in k8s, then recreate them, I get the lhci pod to run just fine, but after a few hours, it'll strangely start failing again with the same port range error

**Comment by annez** [comment]
Hey @patrickhulce wanted to potentially re-open this now we have more information from your #270 . Attempting to run this in a Kube pod, the start-up has these env variables:
```
environment: LHCI_PORT="tcp://10.132.9.76:9001", LHCI_PORT_9001_TCP="tcp://10.132.9.76:9001", LHCI_PORT_9001_TCP_ADDR="10.132.9.76", LHCI_PORT_9001_TCP_PORT="9001", LHCI_PORT_9001_TCP_PROTO="tcp", LHCI_SERVICE_HOST="10.132.9.76", LHCI_SERVICE_PORT="9001", LHCI_SERVICE_PORT_APP_PORT="9001"
```

Which I find awfully strange as there is nothing defined at start up. 

Here is the same pod with `printenv`. LHCI_PORT seems to be a combo of several of the below variables, but looking through the code and yargs I cannot see how this would be inheriting from anywhere.

```
HOSTNAME=lhci-6888699cb8-cm5ks
LHCI_SERVICE_PORT=9001
KUBERNETES_PORT_443_TCP_PROTO=tcp
LHCI_PORT=tcp://10.132.9.76:9001
KUBERNETES_PORT_443_TCP_ADDR=10.132.0.1
KUBERNETES_PORT=tcp://10.132.0.1:443
LHCI_PORT_9001_TCP_PROTO=tcp
PWD=/usr/src/lhci
HOME=/root
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
NODE_VERSION=10.19.0
LHCI_PORT_9001_TCP_ADDR=10.132.9.76
LHCI_SERVICE_HOST=10.132.9.76
KUBERNETES_PORT_443_TCP=tcp://10.132.0.1:443
LHCI_PORT_9001_TCP_PORT=9001
SHLVL=1
LHCI_PORT_9001_TCP=tcp://10.132.9.76:9001
KUBERNETES_SERVICE_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.132.0.1
LHCI_SERVICE_PORT_APP_PORT=9001
```

**Comment by patrickhulce** [comment]
@annez thanks for the additional info. Are you saying that the act of running `lhci` sets all of these variables? Or is that the output of `printenv` above?

I have to believe that these variables are coming from something other than `lhci` it's not even possible to my knowledge for node to modify the environment of a shell that invoked it in a way that `printenv` would recognize.

It is 100% expected and intentional behavior that if `LHCI_PORT=tcp://10.132.9.76:9001` then it would fail with that error.

**Comment by annez** [comment]
Sorry to clarify:
1. First output: the output on error based on your debugging with nothing else set (see below for Kube deployment.yaml
2. Output of same pod, but with `command: ["/bin/bash", "-c", "printenv"]` instead of running default `CMD` from `Dockerfile.

Absolutely not denying that. I have a feeling...  that if your pod is called the same as `lhci`, these ENVs get set. I can validate this quickly, let me get back to you.

Yup that is correct, I was just helping the rest debug their issue with K8S.

**Comment by annez** [comment]
Okay I have found out the issue here @patrickhulce. The system documented in Kubernetes doesn't take into account a deployment or a service being attached (this is how we would set up a Kube system). In the situation of an lhci server we would define:

1. A deployment with LHCI container
2. A service linking to the LHCI container
3. An ingress connected to such service

In the kubernetes world, a `service` linked to a `deployment` automatically creates `SERVICE_PORT` and `SERVICE_HOST` ENV vars. This means if your service is named `lhci` then the env vars filtered down are `LHCI_PORT=tcp://...`. This is the issue people are encountering above.

Should we amend the documentation to highlight this clash?
