### ISSUE TITLE
Delete HTML reports in lighthouseci folder too

### ISSUE THREAD

**Issue by jimbyo** [GoogleChrome/lighthouse-ci#285]
Hello!

I have been trying to set up lighthouse ci and have a few questions. 

1.) I noticed that lighthouse ci can be used with puppeteer, however, Is there a way to use another automated testing software like protractor instead?

2.) Is there a way to disable the storage of lighthouse reports in the /lighthouseci folder or automatically delete them after a certain time? 

Every time I manually run lighthouse tests, the reports are stored in the lighthouse ci folder and just keep piling up.

**Comment by patrickhulce** [comment]
> Is there a way to use another automated testing software like protractor instead?

Not easily but I'm not sure it would help very much even if it were easy. The purpose of puppeteer isn't to run arbitrary flows or any functional tests because Lighthouse is going to ignore the state of the page and reload it anyway. The primary purpose of the puppeteerScript is just to login.

> Is there a way to disable the storage of lighthouse reports in the /lighthouseci folder or automatically delete them after a certain time?

JSON files are cleared out every time you run `collect` without the `--additive` flag, but it looks like there's a bug where HTML reports aren't. We'll fix that :)

**Comment by patrickhulce** [comment]
We'll package this in 0.4.0 though since it has breaking implications for anyone relying on the bug for now.

**Comment by jimbyo** [comment]
> 
Not easily but I'm not sure it would help very much even if it were easy. The purpose of puppeteer isn't to run arbitrary flows or any functional tests because Lighthouse is going to ignore the state of the page and reload it anyway. The primary purpose of the puppeteerScript is just to login.
> 

Oh, I wasn't aware that Lighthouse ignored the state of the page and just reloaded it.
Is this behavior specific to lighthouse-ci or lighthouse in general?

**Comment by patrickhulce** [comment]
Lighthouse in general. It's unrelated to lighthouse-ci.

**Comment by patrickhulce** [comment]
fixed by #318
