### ISSUE TITLE
Warn when trying to use staticDistDir *and* URL at the same time

### ISSUE THREAD

**Issue by safwansamla** [GoogleChrome/lighthouse-ci#287]
I noticed that the output [report](https://googlechrome.github.io/lighthouse-ci/viewer/?baseReport=https%3A%2F%2Fstorage.googleapis.com%2Flighthouse-infrastructure.appspot.com%2Freports%2F1587846431211-47980.report.html&compareReport=https%3A%2F%2Fstorage.googleapis.com%2Flighthouse-infrastructure.appspot.com%2Freports%2F1587921299431-19191.report.html) has a score of 94, which sounded very high. The actual lighthouse report shows that images need to be improved and save as much as 30s.  I compared it by running an audit on web.dev. The score turned out to be 20. I am assuming lhci is running in a local environment so images are loading fast. Is it better to run lhci after deploying the app?

I tried by moving lhci autorun to 'after_deploy' in travis. In my case, I noticed that lhci picked a random port. As a result, it couldn't reach the site in production. 

What's the best way to address this issue?

1. [lhci configuration](https://github.com/safwansamla/Lighthouse-CI-Demo/blob/master/lighthouserc.json)
2. [Travis configuration](https://github.com/safwansamla/Lighthouse-CI-Demo/blob/master/.travis.yml)
3. Travis [Build](https://travis-ci.org/github/safwansamla/Lighthouse-CI-Demo/builds/679788255)

**Comment by patrickhulce** [comment]
> I am assuming lhci is running in a local environment so images are loading fast.

That's not the issue since throttling is applied in both cases. The problem here is that in CI you're testing against the lhci-provided server which uses compression, but you didn't compress your files on heroku. Always compress your files in production.

> In my case, I noticed that lhci picked a random port. As a result, it couldn't reach the site in production.

You can't use both `staticDistDir` *and* a non-localhost `url` at the same time. Either use the built-in server with `staticDistDir` *OR* use your own server and provide a different URL. For your configuration just eliminate the `staticDistDir` property. I've converted this issue to making this more explicit in the documentation.

> Is it better to run lhci after deploying the app?

Yes the more similarities it has to production the better! If you have the ability to test on your actual infrastructure, that's great and would have caught this compression issue in your deployment process. That being said we don't encourage deploying to production production until after you've run LHCI to ensure it passes, but it's up to you if you don't want to setup a separate staging server.

**Comment by safwansamla** [comment]
Quick clarification: If I specify staticDistDir and there are multiple html files in the directory, LHCI runs all of them. Is there a way to specify which URL to run?

**Comment by patrickhulce** [comment]
> If I specify staticDistDir and there are multiple html files in the directory, LHCI runs all of them. Is there a way to specify which URL to run?

Yes, just pick the URL on localhost and pass *that* as your url.

Example for file structure of 
```
|- public
  |- index.html
  |- checkout.html
  |- pricing.html
```

to just run on checkout do 

```
lhci collect --staticDistDir=./public --url=http://localhost/checkout.html
```

**Comment by patrickhulce** [comment]
#302 made this relationship more explicit in the docs, https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#url
