### ISSUE TITLE
Document that LHCI server must own the entire origin

### ISSUE THREAD

**Issue by niklasgrahl** [GoogleChrome/lighthouse-ci#308]
Hi, I'm trying to run the lhci server on a url like 
```
http://dev-server.example.org/dev-tools/lighthouse-ci-server/app/
```
but the server tries to load everything relative to 
```
http://dev-server.example.org/app/
```
 for example `http://dev-server.example.org/app/entry.fd7e7398.js`. It also tries to redirect from `http://dev-server.example.org/dev-tools/lighthouse-ci-server/` to `http://dev-server.example.org/app/`. I can't find any way of setting the asset path at the moment but maybe I am missing something.

**Would you be open to adding a base/public url or asset prefix config option for the server to support this use case?** 

I guess the mount path could be read on server startup but it looks like the asset path is [set at build time](https://github.com/GoogleChrome/lighthouse-ci/blob/b595264ac67dec5afc8cc0b5eaac295ae50f8ac4/packages/server/package.json#L16) so I'm not sure how easy this would be to configure at startup.

It looks like the upload command might already support this use case with the `serverBaseUrl` option, but I haven't tested it. It would be great to have it for the server as well.

Thanks!

**Comment by patrickhulce** [comment]
Thanks for filing @niklasgrahl!

This is a thorny problem that would touch many layers of Lighthouse CI. Not only is the UI affected by every API client as well. The existing `serverBaseUrl` option you point out effectively only supports setting the origin at the moment. In fact I wonder if we should rename this to `serverOrigin` in 0.4.x to make that clearer 🤔 

You're also correct that because the base path is set at build time and we have SPA fake URL paths, any changing of the base path would require a custom build of the frontend code (or a significant rework of how the app references static assets).

Given all of these constraints and the considerable increase in testing surface it would require, I'm not sure this is something we can realistically consider for the near future of the project :/

Happy to add whatever you think would be clear to the server documentation to make this limitation more upfront and obvious!

**Comment by niklasgrahl** [comment]
Thanks for the quick reply! That's ok, I'll see if I can deploy it on a separate subdomain instead 👍 

Cheers!

**Comment by nick-rudenko** [comment]
@niklasgrahl have you managed to make it work using a subdomain? Having the same issue

**Comment by patrickhulce** [comment]
@nick-rudenko subdomain shouldn't require anything special, all the LHCI servers I know of use a subdomain. What issue are you running into with subdomain?

**Comment by nick-rudenko** [comment]
@patrickhulce I haven't tried subdomain yet, just wanted to check if there is any issues because adding a subdomain is out of my scope on the project.

@jflayhart yes, I used redirects in nginx to expose a route `<baseUrl>/tools/lighthouse`. Initially, it was redirecting me to `<baseUrl>/app`. Later, I made it partly work by explicitly plugging all routes from [server.js](https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/server/src/server.js). But it doesn't look like a nice way to go because I need to hardcode each route and locations for the dedicated assets 😥

@jflayhart you mentioned that you are proxying only the `/v1/*` and `/version` endpoints. Could you explain why, please?

Anyway, I think I will try either subdomain or a variant with Heroku. Both are not ideal because there are other tools already running at `<baseUrl>/tools/`.

Thanks!

**Comment by jflayhart** [comment]
@nick-rudenko I think it will becoming more common to proxy this stuff for bigger corporations having locked down servers, etc. Glad you asked! I happen to just write up [a recipe for this setup](https://github.com/GoogleChrome/lighthouse-ci/tree/master/docs/recipes/lhci-server-vpn-proxy).
