### ISSUE TITLE
Expose helper function for fetching the representative report for a given URL.

### ISSUE THREAD

**Issue by WillsB3** [GoogleChrome/lighthouse-ci#335]
In the [open command source](https://github.com/GoogleChrome/lighthouse-ci/blob/a6cf89e5dcbb86db7794ac5b94b7c563119a2ee9/packages/cli/src/open/open.js#L30-L39) there is a helpful bit of code that retrieves the representative Lighthouse report for a given URL.

While working on a module to help integrate Lighthouse CI with GitLab I needed to do the same thing. Since this logic is buried within the open command I was unable to reuse it directly, and so ended up copy+pasting it into my integration modules source.

Would you be open to this logic being extracted to a helper function, perhaps in `@lhci/utils/src/saved-reports.js`?

**Comment by patrickhulce** [comment]
> Would you be open to this logic being extracted to a helper function, perhaps in @lhci/utils/src/saved-reports.js?

I don't think so. We just finished the [`target=filesystem` feature](https://github.com/GoogleChrome/lighthouse-ci/pull/328) which exposes a manifest that identifies the representative report for each run along with properties for the path on disk and we'd prefer folks use *that* instead of reaching into `.lighthouseci` folder or using internal-only methods.

Also worth noting that the median run logic is going to be exposed directly from Lighthouse as well (see https://github.com/GoogleChrome/lighthouse/pull/10859). 

I think the combination of those two are sufficient.

(target=filesystem should be published in 0.4.1 later today)

**Comment by WillsB3** [comment]
Ah - yes, that makes sense, Thanks. I'll update when available and refactor to use the new manifest.

Thanks
