### ISSUE TITLE
Issue upgrading from 3.x.x -> 4.x.x

### ISSUE THREAD

**Issue by tyleroct** [GoogleChrome/lighthouse-ci#347]
- I have upgraded my @lchci/cli@0.4.x
- I have upgraded the server to 0.4.1
- When I try to run the server locally it is trying to serve html 
`entry.fd7e7398.js:1 Uncaught SyntaxError: Unexpected token '<'`
- Didn't see any additional information about upgrading.

**Comment by patrickhulce** [comment]
Thanks for filing @tyleroct!

> When I try to run the server locally it is trying to serve html

How specifically are you running the server? The official docker image? Through the CLI? Mounting the `@lhci/server` module via node yourself?

When I use 0.4.1 and run the server locally via the CLI everything works as expected.

**Comment by tyleroct** [comment]
@patrickhulce I have a server running on our infrastructure with 
```const {createServer} = require('@lhci/server');

console.log('Starting server...');
createServer({
  port: process.env.PORT,
  storage: {
    storageMethod: 'sql',
    sqlDialect: 'sqlite',
    sqlDatabasePath: '/path/to/db.sql',
  },
}).then(({port}) => console.log('LHCI listening on port', port));```

**Comment by patrickhulce** [comment]
Just to clarify, is that snippet exactly what you're running locally with version `0.4.1` when you get `entry.fd7e7398.js:1 Uncaught SyntaxError: Unexpected token '<'`?

Off the bat something is wrong, because that's not the hash for the entry js file in 0.4.1. It should be `entry.ca7b0f06.js`.

`Uncaught SyntaxError: Unexpected token '<'` is also typically a dev server issue when we're trying to use the parcel dev server, but I've never seen it in the production

We have exactly this...

```js
const {createServer} = require('@lhci/server');

console.log('Starting server...');
createServer({
  port: process.env.PORT,
  storage: {
    storageMethod: 'sql',
    sqlDialect: 'postgres',
    sqlConnectionSsl: true,
    sqlConnectionUrl: process.env.DATABASE_URL,
  },
}).then(({port}) => console.log('Listening on port', port));
``` 

running 0.4.1 on our [canary server](https://lhci-canary.herokuapp.com/) without this issue. Maybe poking around that might lead to any clues in configuration differences? I wouldn't expect the server dialect to affect how the static assets are served.

**Comment by tyleroct** [comment]
Thanks @patrickhulce I think the old hash was cached. Liking the tool btw 😄
