### ISSUE TITLE
Unable to upload project by build token

### ISSUE THREAD

**Issue by jflayhart** [GoogleChrome/lighthouse-ci#352]
After running `lhci wizard` successfully, I get the resulting build token to use for uploading. Collecting data with `lhci autorun` works as expected except the get project by token API doesn't work (404):

```
// client cli config
upload: {
      target: 'lhci',
      serverBaseUrl: 'https://custom-server.com/lighthouse',
      token: TOKEN,
      basicAuth: {
        username,
        password
      }
    }

✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  Ancestor hash determinable
✅  LHCI server reachable
⚠️   LHCI server not API-compatible
⚠️   LHCI server token invalid
✅  LHCI server unique build for this hash
Healthcheck passed!

....successful audit completes

Error: Could not find active project with provided token
    at runLHCITarget (/Users/jflayhart/.nvm/versions/node/v13.12.0/lib/node_modules/@lhci/cli/src/upload/upload.js:380:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.runCommand (/Users/jflayhart/.nvm/versions/node/v13.12.0/lib/node_modules/@lhci/cli/src/upload/upload.js:572:16)
    at async run (/Users/jflayhart/.nvm/versions/node/v13.12.0/lib/node_modules/@lhci/cli/src/cli.js:92:7)
WARNING: upload command failed.
assert command failed. Exiting with status code 1.
```

I have curl'd some project endpoints y'all use in your source code and /projects returns this:

```
// GET https://custom-server.com/lighthouse/v1/projects
[
    {
        "id": "123-abc",
        "name": "repo-name",
        "token": "", // empty!
        "adminToken": "", // empty (although not set in GUI)
        ...
    }
]
```

Any ideas what could be going on with project creation? I am definitely using the correct build token that was provided from wizard and PostGres is stable.

**EDIT:** I just found you clear the tokens in response intentionally, which is sane: https://github.com/GoogleChrome/lighthouse-ci/blob/master/packages/server/src/api/routes/projects.js#L27

So I tried `POST https://custom-server.com/lighthouse/v1/projects/lookup` with token and get 200:

```
{
    "id": "123-abc",
    "name": "repo-name",
    "token": "ACTUAL TOKEN",
    ...
}
```

lol what gives?

**Comment by jflayhart** [comment]
Found the issue. I had correctly set my BASE URL to be `serverBaseUrl: 'https://custom-server.com/lighthouse',` however, LHCI autorun is attempting to find an endpoint on the INCORRECT baseurl of `serverBaseUrl: 'https://custom-server.com/`

Thus 404! I can look into a fix for this

STDOUT log:
```
✅  LHCI server reachable
⚠️   LHCI server not API-compatible

findProjectByToken TOKEN
_fetchWithRequestBody { token: TOKEN }
_convertFetchResponseToReturnValue Body {
  url: 'https://staging-api.shipt.com/v1/projects/lookup', // WRONG baseUrl!
  status: 404,
  statusText: 'Not Found',
```

**Comment by jflayhart** [comment]
Why not simply concat the root url and endpoint?

**Comment by patrickhulce** [comment]
> Why not simply concat the root url and endpoint rather than depending on this core node lib, url?

It seems you've already stumbled onto the reason why. #308, everything in LHCI is written with the assumption that the server owns its origin.

> new this._URL(url, this._rootURL)

This is used specifically to reuse just the origin and normalize `https://server.com` and `https://server.com/` etc

> ⚠️   LHCI server not API-compatible

Is this just because of the proxying issue you're doing or is there actually a version mismatch between the client and the server? That would also cause problems.

Seems like this boils down to the same ask as https://github.com/GoogleChrome/lighthouse-ci/issues/308#issue-618132178 which is to remove this requirement. Is that fair?

**Comment by jflayhart** [comment]
@patrickhulce weird... it seems the `/version` endpoint is also hitting the wrong base url: `custom-server.com/version` instead of `custom-server.com/lighthouse/version`, so your insight into a version match explains why that's an issue! Interesting that it's considered reachable though...

**Comment by jflayhart** [comment]
Help me understand something, but is it assuming that the client config and serve config exist in the same rc file? Cause then I think I get your point, if we set a baseUrl for both client CLI _and_ server, the server needs to access the origin for reasons.

Although I am operating under multiple clients are connecting to this separate CI server where the baseUrl is decoupled from servert setup and I would argue should be used in its entirety. I'm not understanding why we need the origin or host for the CLI? Can't it just use what we tel it to use by setting `serverBaseUrl`? Trying to understand that bit...

**Comment by patrickhulce** [comment]
>  is it assuming that the client config and server config co-exist in one rc file?

No, not necessarily. Just that by far the predominant deployment method has people accessing the UI through the same origin that they upload to. 

e.g. we use `https://lhci-canary.herokuapp.com` we go to that URL to see the UI and it's the same URL that the server uploads to. There's no real fancy split in the LHCI server code for the backend and the UI, so it's always hitting the same server and most people thusfar use the same URL when using both. Because of that we don't want to enable a configuration early on that will inevitably break later when they try to look at their data.

The VPN setup is very cool though, and it makes sense. I'm open to enabling this if we just document how to accomplish the other half so people don't end up shooting themselves in the foot.
