### ISSUE TITLE
Add message to dashboard popover that it can be held open by clicking on a build point

### ISSUE THREAD

**Issue by jflayhart** [GoogleChrome/lighthouse-ci#357]
First of all, love the GUI. I think it's cool to be able to drill down in graphs on the dashboard, but this in particular is not working when I want to click on "report" or "ci diff":
![kQuiu3e429](https://user-images.githubusercontent.com/6808172/85572539-b157e380-b5fa-11ea-8436-dd5512a638e0.gif)

Using latest chrome browser

**Comment by patrickhulce** [comment]
This is intended behavior to allow scrubbing through graphs where points are clustered very close together. 

The intended flow is to click on the point to freeze the popover, but that's basically impossible to figure out since the cursor doesn't change :)

We'll fix the cursor issue that seems to have regressed 👍

**Comment by patrickhulce** [comment]
Hm, I can't reproduce this issue on latest stable Chrome or Chrome Canary or Firefox or Safari I see the cursor as a pointer prompting you to click.

Any extra info you have for me to help there?

**Comment by gauthampughaz** [comment]
@patrickhulce I am facing the same issue as well.
I am using stable chrome "Version 83.0.4103.106 (Official Build) (64-bit)" on MacOS X Catalina and @lhci/server version 0.4.1

It worked fine for the first popup in the video (zipped) except for the flickering caused due to pointer change. But for the second and third popups, I was not able to click the CI diff option.

I think the problem occurs when the popup has a performance difference (colored one) inside it, which causes the popup along with options to go below the graph line.

[popup_issue.zip](https://github.com/GoogleChrome/lighthouse-ci/files/4830699/popup_issue.zip)

**Comment by patrickhulce** [comment]
Thanks @gauthampughaz I can reproduce what you're talking about when there is very little data on the server 👍 

The intended behavior though as stated in https://github.com/GoogleChrome/lighthouse-ci/issues/357#issuecomment-648898501 is to *click* on the point you'd like to freeze and then feel free to explore the data for the build rather than relying on fast mouse movements to whip over to the popover. 

I understand it's optimized for the use case once there is a lot of data on the server, so if there are ideas for how to make this clearer than the cursor pointer, definitely open to contributions! :)

**Comment by jflayhart** [comment]
What about a more clear UX like a small info tip or some text explaining "click on point to extend popup"? Or do you think it should be implied for dumb users like me? 😉

**Comment by jflayhart** [comment]
Actually, I am seeing the pointer now! I guess this is OK 👍

**Comment by patrickhulce** [comment]
Thanks for the suggestions @jflayhart you're not a dumb user! :) It's not obvious, and I can see the confusion potential. 

> What about a more clear UX like a small info tip or some text explaining "click on point to extend popup"?

This sounds good to me! Any takers for a PR?
