### ISSUE TITLE
add a `healthcheck` command

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse-ci#38]
ref #26 

In https://travis-ci.org/GoogleChrome/web.dev/builds/604263335#L634 i was hoping to see the new github status i just added the token for
so i hit "restart" but it errored because the hash was already uploaded. :(

but maybe instead of erroring we just overwrite the previous data with the newest one?
last one wins seems slightly more reasonable than first one wins.

(I don't know how codecov, etc handle this case. Probably something well considered.) 

i'm sure in the future we'll have a more complicated solution, but wdyt about this for now?

**Comment by patrickhulce** [comment]
I have a few concerns for using last one wins:

1. overwriting data seems problematic, especially when, so far, public tokens can't really do damage that new PRs couldn't do. if they could start erasing old data that could be really bad, without more sophisticated authenticity verification with the CI provider i'm not sure this could fly.
2. *silently* overwriting data seems extra problematic, the bonus of the error is that it flags for you that you've configured things incorrectly in matrix build situations. I'd prefer to only expose this behind some sort of `--force ` flag, but that wouldn't actually work in your use case because a new commit would eliminate the need for the flag in the first place
3. the overwriting of historical data poses complications for the pipeline that computes statistics over the runs, not impossible to engineer around or anything but a considerable amount of complexity to add especially given the first two issues

**Comment by paulirish** [comment]
1. yahhh
1. true true.
1. yah that def sucks.

-------

I have a terrible idea but its related to this and #36 and #34 

Basically the thing in common is that the LHCI run failed but it was after collection. Makes the iteration time of setting things up extra long. 

Terrible idea: a "health check" stage run at the beginning of `collect`. There we check for no merge-base, alert on lack of github header, alert that the build hash already exists (depending on our policy here). 

Seems like a lot of complexity but then again "setting up" only happens once and after that everything should just be automatic so this is where we'll face most of our user friction. 🤷‍♂

**Comment by patrickhulce** [comment]
> Basically the thing in common is that the LHCI run failed but it was after collection. Makes the iteration time of setting things up extra long.

ya true this is extra painful

> a "health check" stage

I like this idea as a separate command and part of autorun+example scripts :) the reason I want an opt-in for this is that there are very valid and legit use cases where you don't care about a merge-base or the github token at all so preventing you from collecting by default seems bad. we do at least know from the rcfile if you intend to upload to an lhci server but not if github integration is required

strawman api

`lhci healthcheck [--fatal] [github] [lhci-server-upload] [temporary-public-storage]`?

**Comment by paulirish** [comment]
ya cool.

i'm hesitant to commit to specific items in this list so i almost feel like right now `--all` is either required or implied. and we'll only let you do specifics in the future once are names are more concrete? 

```sh
lhci healthcheck [--fatal] --all
```

but w/e i'm cool with yours.
