### ISSUE TITLE
Upgrade Lighthouse version from 6.0.0 to 6.1.1

### ISSUE THREAD

**Issue by chosak** [GoogleChrome/lighthouse-ci#399]
This package is currently pinned to Lighthouse 6.0.0 ([for example](https://github.com/GoogleChrome/lighthouse-ci/blob/1bf2e963766214111787d616ef45f198912cfb79/packages/cli/package.json#L22)), but there have been [two releases](https://github.com/GoogleChrome/lighthouse/releases) since then.

Using version 6.1.1 does fail a few of the existing tests (see log [here](https://gist.github.com/chosak/cdf3006a85001334099acad9b1d48950)), but at first glance these are hopefully minor things having to do with the new audits (long-tasks and crawable-anchors) and diffs in output due to [trailing slashes in web.dev links](https://github.com/GoogleChrome/lighthouse/pull/10967).

If a PR fixing these failures and bumping the version would be welcome, would it be appropriate to use `^6.1.1` or `~6.1.1` to automatically use new minor or patch releases?

**Comment by patrickhulce** [comment]
Thanks for filing @chosak! We definitely will. Since 6.1 of Lighthouse introduced new audits to a scored category which means that scores will drop for users who are currently failing that audit. According to [our more rigorous version policy](https://github.com/GoogleChrome/lighthouse-ci/blob/1bf2e963766214111787d616ef45f198912cfb79/docs/version-policy.md#cadence), that counts as a breaking change. There were a few high value fixes worth waiting for 6.2.0 for, so I'm inclined to give it a bit more time.

**Comment by chosak** [comment]
Thanks @patrickhulce, I hadn't seen that doc page. :+1:

**Comment by thuey-nelnet** [comment]
Will there be an update for lighthouse 6.2.0 soon? It looks like it should include a patch for [CVE-2020-8116](https://github.com/advisories/GHSA-ff7x-qrg7-qggm) in configurator.

**Comment by patrickhulce** [comment]
Yeah we'll update to 6.2.0 soon.
