### ISSUE TITLE
Difference in score between lighthouse-ci and chrome lighthouse tool generated results

### ISSUE THREAD

**Issue by gauthampughaz** [GoogleChrome/lighthouse-ci#479]
@patrickhulce I am facing an issue where there is a considerable difference in score between the chrome generated and the lighthouse-ci generated results, especially the performance score for quora. Is it acceptable or is this something that should be addressed?

Attaching the screenshots and the JSON files for your reference.
<img width="1536" alt="Application - Quora" src="https://user-images.githubusercontent.com/11377638/97554294-90662b80-19fc-11eb-8af3-7a84cdde5246.png">
<img width="1536" alt="Chrome - Quora" src="https://user-images.githubusercontent.com/11377638/97554341-9e1bb100-19fc-11eb-86b8-5a40dc02652d.png">
[Results.zip](https://github.com/GoogleChrome/lighthouse-ci/files/5457557/Results.zip)

**Comment by gauthampughaz** [comment]
@patrickhulce the machine, the lighthouse versions, and the chrome versions used to generate the results were the same, which you can verify using the JSON results.

**Comment by patrickhulce** [comment]
Appreciate the filing of this @gauthampughaz but we don't have the capacity to be able to help debug this sort of issue further. I've added [this shortcut FAQ](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/troubleshooting.md#the-results-im-seeing-dont-match-the-results-i-see-in-another-environment) to our docs, but that's about the extent of what we can do right now.

I hope you figure out the discrepancy and please share if you do so that others who stumble on this issue may be aware of it in the future! :)
