### ISSUE TITLE
Unable to run lhci command

### ISSUE THREAD

**Issue by waniparag** [GoogleChrome/lighthouse-ci#493]
Hi I have tried installing lhci using the following command

npm install @lhci/cli (version .6) as mentioned in the documentation.

When i try to run the lhci autorun command  for eg : C:\lighthouse\lighthouse-ci>lhci autorun it gives me a error everytime. it used to work in the past but i am not able to run it now, I have tried to add path to environment variables,restarted my machine few times but no luck. Can you please guide why this is happening @patrickhulce ?
![lhcierror](https://user-images.githubusercontent.com/53806666/99324621-cd6d6180-28c8-11eb-8b3c-ffd4f7a03b78.png)

**Comment by patrickhulce** [comment]
> npm install @lhci/cli (version .6) as mentioned in the documentation.

Which documentation instructed you to leave off `-g` so we can update it?

If you install it locally only, `lhci` needs to be part of an npm script, invoked with `npx` or its complete path at `./node_modules/.bin/lhci`

**Comment by waniparag** [comment]
Hi @patrickhulce thanks for the response. That was a typo the actual command was npm install -g @lhci/cli , I have been following the starter pack example as well https://github.com/hchiam/learning-lighthouse-ci and i get the same error ,The lhci package doesnt get installed at all, Is there an existing issue with the package itself ?

**Comment by patrickhulce** [comment]
> The lhci package doesnt get installed at all, Is there an existing issue with the package itself ?

No, and that's not what I'm seeing with your screenshots either. I'm seeing what looks like path issues mixed with a slight misunderstanding of `npx` :)

```
$ docker run -it --entrypoint /bin/bash node:12-buster
Unable to find image 'node:12-buster' locally
12-buster: Pulling from library/node
e4c3d3e4f7b0: Pull complete
101c41d0463b: Pull complete
8275efcd805f: Pull complete
751620502a7a: Pull complete
0a5e725150a2: Pull complete
7e1f45686e96: Pull complete
16781af4fb61: Pull complete
b6fa0faab1fc: Pull complete
6b0776b36bc3: Pull complete
Digest: sha256:8b360177f70a5fd38d11c0aa102cab4bc05cf008f0a9dcf8cde6a77e1154d4e5
Status: Downloaded newer image for node:12-buster

root@d671fe438903:/# npm install -g @lhci/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/lhci -> /usr/local/lib/node_modules/@lhci/cli/src/cli.js
+ @lhci/cli@0.6.1
added 423 packages from 266 contributors in 26.853s

root@d671fe438903:/# lhci --help
lhci <command> <options>

Commands:
  lhci collect      Run Lighthouse and save the results to a local folder
  lhci upload       Save the results to the server
  lhci assert       Assert that the latest results meet expectations
  lhci autorun      Run collect/assert/upload with sensible defaults
  lhci healthcheck  Run diagnostics to ensure a valid configuration
  lhci open         Opens the HTML reports of collected runs
  lhci wizard       Step-by-step wizard for CI tasks like creating a project
  lhci server       Run Lighthouse CI server

Options:
  --help             Show help                                                                                         [boolean]
  --version          Show version number                                                                               [boolean]
  --no-lighthouserc  Disables automatic usage of a .lighthouserc file.                                                 [boolean]
  --config           Path to JSON config file
```

If you're new to npm on Windows I'd suggest trying to run the examples in the docs in a bash environment on Windows ([Git bash](https://gitforwindows.org/) is pretty helpful, or WSL even better) or getting more familiar with how Windows command prompt from bash to be able to translate online examples.

For each of your examples and why they don't work...

- The global modules said they were installed at ~/AppData/Roaming/npm which I'm guessing isn't in your path
- LHCI isn't installed locally so it won't be in that folder, it's in `~/AppData/Roaming/npm` according to that top command
- This isn't a bash shell so `./` isn't the pattern you want to use
- Dropping `.` doesn't help because that means start at the root of your disk
- It wouldn't be `npx run <path to file>`, it'd be `npx -p @lhci/cli lhci --help`
