### ISSUE TITLE
Median report not generating in case of target as filesystem 

### ISSUE THREAD

**Issue by ashishkshrivastava** [GoogleChrome/lighthouse-ci#503]
Hello,

I have to send email with a median report of multiple runs of a specific URL.I followed the  (https://github.com/GoogleChrome/lighthouse-ci/issues/142)  link but even after that, I could not see the reports. As I have given numberOfRuns=2 so I can see the reports in the artifacts folder but that is not the median report it contains all reports, I mean multiple HTML and JSON.

**Steps i have done**  
1)  In .lighthouserc.js file I added 
      
      target: "filesystem",
      outputDir: "./lhci",
      reportFilenamePattern: "%%HOSTNAME%%-%%PATHNAME%%-%%DATETIME%%.report.%%EXTENSION%%"

2)  I am not sure but I created **manifest.json**  in my repo within **lhci**

In the pipeline console, I can see a message report dumped in /builds/githubusername/lighthouse-test/lhci...  but I am not sure how to access this if this correct path and median report.As per my understanding reports should be dumped in my repo directory **lhci folder** and the manifest file should be updated with file name details.
 
I have few more questions.

1) How can I  store assertion result and reports in artifacts in case of assert failure if am using the filesystem as storage?
2)  how can I give my cloud bucket path to store reports.
3) Is there any way to give an option to select the page to test?
4) Can I have the **assert-result.json** in case of target="temporary-public-storage".
5)  Which parameter will give the value of generated median report URL in case of temporary-public-storage. I have to use that parameter value in the git yml file for further processing. for example (https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1607-52943301.report.html)
6) Is there any way I will have reports generated in artifacts or somewhere else (in the filesystem) also assertion results in the case of assert check fail. 

I would appreciate it if you answer my question on priority. I am totally new in this world so please consider my questions

Thanks & Regards
Ashish

**Comment by patrickhulce** [comment]
Thanks for filing @ashishkshrivastava! Since you're new, here are some general guidelines for what's appropriate for a GitHub issue compared to another forum :)

Generally, file an issue and expect a response from a maintainer when...

- You've found a bug with clear reproduction steps.
- Document is incorrect or completely missing.
- You have an idea for new functionality you'd like to share for discussion.
- You've thoroughly searched previous issues for related problems and haven't found anything.

Generally, avoid filing an issue and/or don't expect a response from a maintainer when...

- You're wondering how stuff works.
- You'd like help fitting the project into your specific workflow.
- Any other questions that wouldn't require changes to the project or be uniquely answered by project maintainers.

This second set of questions is better handled by community discussions (which maintainers also participate in 😃) and places like IRC/Discord/Gitter/chat rooms, GitHub discussions (when available), or other forums like Stack Overflow. 

----------------------------------------

Many of these questions are answered by the [configuration](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md) and [getting started documentation](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md).

I cannot reproduce the issue you describe and things are working [as documented](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#outputdir).

```bash
$ npm install -g @lhci/cli
$ lhci collect --url=https://example.com
Running Lighthouse 3 time(s) on https://example.com
Run #1...done.
Run #2...done.
Run #3...done.
Done running Lighthouse!
$ lhci upload --target=filesystem --outputDir=./lhci
Dumping 3 reports to disk at /home/lhci/reports/lhci...
Done writing reports to disk.
$ ls lhci
example_com-_-2020_12_04_15_59_37.report.html
example_com-_-2020_12_04_15_59_37.report.json
example_com-_-2020_12_04_15_59_43.report.html
example_com-_-2020_12_04_15_59_43.report.json
example_com-_-2020_12_04_15_59_48.report.html
example_com-_-2020_12_04_15_59_48.report.json
manifest.json
$ grep 'isRepresentativeRun.*true' lhci/manifest.json -A 2
    "isRepresentativeRun": true,
    "htmlPath": "/home/lhci/reports/lhci/example_com-_-2020_12_04_15_59_43.report.html",
    "jsonPath": "/home/lhci/reports/lhci/example_com-_-2020_12_04_15_59_43.report.json", 
```
