### ISSUE TITLE
Gitlab CI - PROTOCOL_TIMEOUT error

### ISSUE THREAD

**Issue by kresogalic8** [GoogleChrome/lighthouse-ci#504]
I have a setup which is shown below and I constantly get the error for timeout.  

**.gitlab-ci.yml**
`pbs:performance:
  image: node:12-alpine
  stage: performance
  needs: []
  before_script:
    - apk update && apk add openjdk8-jre
    - apk add --update py3-pip
    - pip3 install awscli
    - apk add --no-cache chromium
  script:
    - *setupAWS
    - *aws_ci_apiBuild
    - npm install
    - npm run build
    - npm install -g @lhci/cli@0.6.x
    - lhci autorun`

**Error**
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions)
LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/@lhci/cli/node_modules/lighthouse/lighthouse-core/gather/driver.js:371:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Logs/Screenshots**
![Screenshot 2020-12-08 at 11 04 57](https://user-images.githubusercontent.com/7289406/101469628-48182280-3945-11eb-8766-af3a30eb096d.png)

**Comment by patrickhulce** [comment]
Thanks for filing @kresogalic8! Unfortunately there's not much we can do about this on the LHCI side. The https://github.com/GoogleChrome/lighthouse/issues/6512 issue thread covers all the different reasons this can be happening.

Since you're using docker images you might have success with the `--disable-dev-shm-usage` Chromium flag (see [custom chrome flag docs](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#custom-chrome-flags)), but other than that it's on Chromium to resolve these timeouts :/

**Comment by MrCsabaToth** [comment]
The reason for the timeout is that LHCI tried to run the test against `https://www.misterspex.de:63388`. The `63388` port won't be open on the public server. Currently I rewrote my `.lighhouserc.json` to refer to `https://localhost`, as you can see that's where the job starts the server to test. Then just like with the public domain it'll run the test against `localhost:63388` and it won't time out. See also https://stackoverflow.com/questions/70329628/lighthouse-gitlab-ci-for-a-jekyll-website-times-out/
