### ISSUE TITLE
Allow multiple uploads

### ISSUE THREAD

**Issue by derz** [GoogleChrome/lighthouse-ci#543]
Hi, first of all: thanks for the great work on lighthouse + lhci so far - it really eased up our development (and also brought some more attention to performance on the client side) :-)

We're currently publishing the audit results to a lighthouse-server instance, however we would love to be able to also upload them to the filesystem. Therefore it would be nice if we could define multiple upload targets, for example like so:

```js
	upload: [
		{
			target: 'lhci',
			serverBaseUrl: '...'
		},
		{
			target: 'filesystem',
			outputDir: './lhci',
		},
	]
```

I also tried to just use the content of `.lighthouseci`, however that's rather cumbersome compared to the `target: 'filesystem'` output, since there it is already nicely formatted/prepared & parsable through the `manifest.json`.

Happy to contribute here by myself if that's something you're considering to be useful.

**Comment by patrickhulce** [comment]
Thanks for filing @derz! For now you can just run `lhci upload` again with a different config to upload the results to another target. 

I see the value in this, but making it work with yargs while preserving backcompat with existing configs is going to be very very difficult because `upload` is the entire argument object of the command itself. Maybe if it were a child property of `upload` it would be easier? `upload: {multiTargets: [{target: 'foo'}]}` or something?

I imagine that might get confusing with the validation and demanding that the root `target` be set, do we need to check that no other properties are defined at the root if `multiTarget` is used, etc.

Not saying no, but there are *a lot* of challenges to work through for something that already works today with an extra line + a file or two. If you're willing to work through all of them and put up a PR, we can discuss in more detail there.

**Comment by derz** [comment]
Hey @patrickhulce, thanks for the fast response. Somehow I didn't think about just adding an additional command at all, I was too focused on the config file itself 🙈. I think as a workaround that's fine enough and not worth the hassle, so let's close the issue. Thanks again!
