### ISSUE TITLE
Provide CSV output option as supported by lighthouse

### ISSUE THREAD

**Issue by everflux** [GoogleChrome/lighthouse-ci#651]
**Is your feature request related to a problem? Please describe.**

I want to extract audit values from lhci run using CSV output.
The switch `--collect.settings.output=csv` is not supported.

**Describe the solution you'd like**
Support CSV in addition to JSON output to file (and/or stdout).

**Describe alternatives you've considered**
Using lighthouse without lhci 

**Additional context**
I want to run a stateless docker container that uses a file mount during CI

**Comment by patrickhulce** [comment]
Thanks for filing @everflux!

This is explicitly not supported and will not be supported because LHCI requires the JSON output to power all of its features. I strongly recommend using the JSON output for your use case as well. It's fairly trivial to convert to a CSV in your ideal format once you have the JSON too :)

**Comment by everflux** [comment]
Thanks for looking into it. Converting to CSV from JSON using a small node script is indeed a viable option, thanks for pointing that out.
