### ISSUE TITLE
TypeError: Converting circular structure to JSON when closing server comparison details

### ISSUE THREAD

**Issue by dkarzon** [GoogleChrome/lighthouse-ci#666]
**Describe the bug**
While comparing runs on the server after clicking on an audit node for details and error is thrown when the details flyout is closed making it unable to be closed.

**To Reproduce**
1. Open a project and click on the latest build from the builds list to compare it to the previous.
2. Click on any audit node in the list to open the details flyout.
3. Click the X at the top right of the flyout to close it.

**Expected behavior**
The details flyout should close properly when the x button is clicked.

**Logs/Screenshots**
If applicable, add LHCI logs or screenshots to help explain your problem.

Link to LHR JSON (2021-08-05) https://drive.google.com/file/d/10aacNRUBT6pTlRDPTUcOU4bF9ETbjtTV/view?usp=sharing
Link to LHR JSON (2021-08-06) https://drive.google.com/file/d/10ed70c0r_hwdKdWqX-q6L8RLxK8sx1nq/view?usp=sharing

![image](https://user-images.githubusercontent.com/214449/128441469-dee72e0c-51fe-418a-ad94-d507e20a8a7c.png)

**Environment (please complete the following information):**
 - OS: Docker on Windows 10
 - Server: LHCI Server v0.8.0
 - Browser: Chrome (92) & Edge (92)

These reports were generated using the servers PSI collection cron job (Lighthouse v8.0.0) not by the lhci cli.

Not sure if this is related or not but the Cumulative Layout Shift details section shows the raw json in the details flyout.
![image](https://user-images.githubusercontent.com/214449/128442138-d9e260a2-d237-470d-a3d6-c65900f2d253.png)

Also note, this error doesn't seem to happen if the reports are generated from LHCI CLI (v0.8.0) directly.

**Comment by patrickhulce** [comment]
Thanks very much for reporting @dkarzon! We'll look into what's up with the PSI payloads 👍

**Comment by patrickhulce** [comment]
Wow, this is a fun one. 

Somewhere along the rendering path preact seems to be mutating the objects passed in as props with state annotations

![image](https://user-images.githubusercontent.com/2301202/128527530-8c5ceec6-9411-4359-8ccf-21b9584e85cf.png)

The first pass renders fine because it's just the plain object being analyzed, as expected. When anything triggers a rerender though (such as closing the sidebar), the preact annotations cannot be serialized and we get this error seen above.

Unclear why this only happens with the PSI report, but don't really have time to investigate. I'll just do the quick fix of ignoring the preact properties for now. If anyone wants to dig deeper, this could get very interesting :)

**Comment by dkarzon** [comment]
Great thanks. I haven't been able to get the source building locally just yet but hopefully I can soon then maybe I will have a look into it.

**Comment by ntkoopman** [comment]
I have the same issue without PSI. Can confirm it works on the latest master though.
