### ISSUE TITLE
Document how to not make Travis fail

### ISSUE THREAD

**Issue by mauriciabad** [GoogleChrome/lighthouse-ci#77]
If I run Travis without Lighthouse it passes all the tests.
When I add Lighthouse the test fails because my app is not optimized yet.
But when Lighthouse fails Travis also fails.

I only use Travis for checking syntax style and linting, not for running tests. 
So, in my case, the ideal behavior would be that when Lighthouse finishes its tests just updates the GitHub status, but not making Travis fail.

Can this be added as a CLI Command or as an option in `lighthouserc.json`?

Thanks, 

_btw: I love this tool, you are doing a great job_

**Comment by patrickhulce** [comment]
Thanks very much for filing @mauriciabad! We're restructuring the docs to nudge people in this direction as well so you're not alone :)

If you don't want to fail travis builds based on Lighthouse you can move the `lhci autorun` command to the `after_success:` list of travis commands instead of `script:`, i.e.

```yaml
after_success:
  - lhci autorun
```

**Comment by patrickhulce** [comment]
FWIW, we also think it's a great idea to still assert `lighthouse:recommended` but disable the rules you're currently failing in your lighthouserc.json to at least prevent regressions in the meantime. Then PRs that fix the issues can slowly reenable the audits. We're working on a command that would autogenerate such a lighthouserc.json file for you :)
