### ISSUE TITLE
CSS chunk is served with incorrect Content-Type header

### ISSUE THREAD

**Issue by dakoenig** [GoogleChrome/lighthouse-ci#875]
**Describe the bug**
The CSS chunk /app/projects/{name}/chunks/entry-{hash}.css is served with a "Content-Type: text/html" header when refreshing a project related page (see screenshot 1).
This results in the styles not being applied and the page looking broken as a result.
This happens for every page after selecting a project (dashboard, diff view, settings, ...)

**To Reproduce**
1. Host a LHCI server (e.g. via lhci server or the Docker image)
2. Create a new project or use an existing one
3. Go to the domain the server is hosted at (http://localhost:9001)
  The dashboard looks normal
4. Select a project
  The project dashboard (or any other project related page) looks normal
5. Refresh the page
  The project dashboard (or any other project related page) looks broken (see screenshot 2)

**Expected behavior**
The project dashboard should look normal after a page refresh.

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/15033519/220616441-7bb81706-33c7-4d5a-957a-b891c04597b2.png)
![image](https://user-images.githubusercontent.com/15033519/220619256-503a3250-064b-4bad-95a8-49d2b164214c.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 110

**Additional context**
Happens for other browsers as well.

**Comment by manelmadeira** [comment]
I have this problem in `v0.11.0` but not in `v0.10.0`.

**Comment by dakoenig** [comment]
Yeah, forgot to add that this is a regression in `v0.11.0`.

**Comment by chaimabg** [comment]
I had the same problem, and it looks like when refreshing a page related to the project (dashboard, diff view, settings, ... but not the projects page), the request URL for the CSS chunk is invalid (because it's a relative URL) which is why it returns the html file (index.html) responsible for loading the chunk.

<img src="https://user-images.githubusercontent.com/60293064/222377427-2a572659-b5c4-41f3-b501-fd65ada5f5e9.png"  width="500" height="400">
Valid CSS chunk path: /app/chunks/entry-{hash}.css
