### ISSUE TITLE
Latest docker server  patrickhulce/lhci-server breaks UI on page refresh

### ISSUE THREAD

**Issue by mihalikv** [GoogleChrome/lighthouse-ci#884]
**Describe the bug**
If you go to some project or other non-homepage URL, and hit refresh(F5), the whole site is broken.

**To Reproduce**
1. Go to '/app/projects/${project}/dashboard'
2. Hit refresh
3. Site will be broken

**Expected behavior**
The site should work also after a refresh

**Logs/Screenshots**
https://user-images.githubusercontent.com/10236315/223979316-6506967d-e56a-4d24-ab5d-f90e055a8960.mp4

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome 110.0.5481.178
 - Version: patrickhulce/lhci-server:latest

**Additional context**
I test it also with patrickhulce/lhci-server:0.10.0 and it works fine even after refresh.

**Comment by sandrodesouza** [comment]
https://github.com/GoogleChrome/lighthouse-ci/issues/893#issuecomment-1499270991

**Comment by paulirish** [comment]
Thanks for reporting! 

This is fixed in https://github.com/GoogleChrome/lighthouse-ci/pull/879 
Which was released in lhci v0.11.1
A matching new release of the `patrickhulce/lhci-server` docker image also shipped yesterday.

And FYI we have a new release of lhci coming which bumps the LH version used to 10.x. You can watch #891 for updates on that.
