### ISSUE TITLE
With new patrickhulce/lhci-server server UI broken almost maximum place 

### ISSUE THREAD

**Issue by akqaaditya** [GoogleChrome/lighthouse-ci#892]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/38026817/227920614-c964ba70-4721-4385-bdc5-00d5fca6ee4a.png">

**Comment by sandrodesouza** [comment]
https://github.com/GoogleChrome/lighthouse-ci/issues/893#issuecomment-1499270991

**Comment by paulirish** [comment]
Thanks for reporting! 

This is fixed in https://github.com/GoogleChrome/lighthouse-ci/pull/879 
Which was released in lhci v0.11.1
A matching new release of the `patrickhulce/lhci-server` docker image also shipped yesterday.

And FYI we have a new release of lhci coming which bumps the LH version used to 10.x. You can watch #891 for updates on that.
